language: csharp
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      dotnet: 2.1.0
      mono: none
    - os: linux
      dist: bionic
      sudo: required
      dotnet: 2.0.0
      mono: none
branches:
  only:
    - master
    - develop
script:
  - dotnet restore "src\main" 
  - dotnet build "src\main" -f netstandard2.0
  - dotnet restore "src\test"
  - dotnet build "src\test" -c Release
  - dotnet test "src\test\Hangfire.JobsLogger.Test.csproj" --configuration Release --no-build