version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    branches:
      only:
        - master
        - develop
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Restore Packages"
          command: dotnet.exe restore "src\main"
      - run:
          name: "Build App"
          command: dotnet.exe build "src\main" -f netstandard2.0
      - run:
          name: "Run unit testing"
          command: dotnet.exe test "src\test\Hangfire.JobsLogger.Test.csproj" --configuration Release --no-build